TIMESTAMP_PATTERNS = [
    # === ISO 8601 variants (highest confidence) ===
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{1,6}Z\b",
        "format": "%Y-%m-%dT%H:%M:%S.%fZ",
        "name": "iso8601_utc_ms",
        "base_confidence": 0.98,
        "specificity": "high",
        "has_timezone": True,
        "has_microseconds": True,
    },
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\b",
        "format": "%Y-%m-%dT%H:%M:%SZ",
        "name": "iso8601_utc",
        "base_confidence": 0.95,
        "specificity": "high",
        "has_timezone": True,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?[+-]\d{2}:\d{2}\b",
        "format": "%Y-%m-%dT%H:%M:%S%z",
        "name": "iso8601_tz",
        "base_confidence": 0.92,
        "specificity": "high",
        "has_timezone": True,
        "has_microseconds": True,
    },
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?\b",
        "format": "%Y-%m-%dT%H:%M:%S.%f",
        "name": "iso8601_naive",
        "base_confidence": 0.85,
        "specificity": "high",
        "has_timezone": False,
        "has_microseconds": True,
    },
    # === RFC 2822 (email standard) ===
    {
        "pattern": r"\b[A-Za-z]{3},\s+\d{1,2}\s+[A-Za-z]{3}\s+\d{4}\s+\d{2}:\d{2}:\d{2}\s+[+-]\d{4}\b",
        "format": "%a, %d %b %Y %H:%M:%S %z",
        "name": "rfc2822",
        "base_confidence": 0.90,
        "specificity": "high",
        "has_timezone": True,
        "has_microseconds": False,
    },
    # === Server log formats ===
    {
        "pattern": r"\b[A-Za-z]{3}\s+[A-Za-z]{3}\s+\d{2}\s+\d{2}:\d{2}:\d{2}\s+\d{4}\b",
        "format": "%a %b %d %H:%M:%S %Y",
        "name": "apache_modjk_bracketed",
        "base_confidence": 0.88,
        "specificity": "high",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{2}/[A-Za-z]{3}/\d{4}:\d{2}:\d{2}:\d{2}\s+[+-]\d{4}\b",
        "format": "%d/%b/%Y:%H:%M:%S %z",
        "name": "apache_common",
        "base_confidence": 0.87,
        "specificity": "medium",
        "has_timezone": True,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{2}/[A-Za-z]{3}/\d{4}:\d{2}:\d{2}:\d{2}\b",
        "format": "%d/%b/%Y:%H:%M:%S",
        "name": "apache_common_no_tz",
        "base_confidence": 0.82,
        "specificity": "medium",
        "has_timezone": False,
        "has_microseconds": False,
    },
    # === Python logging with millis ===
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2},\d{3}\b",
        "format": "%Y-%m-%d %H:%M:%S,%f",
        "name": "python_logging",
        "base_confidence": 0.90,
        "specificity": "high",
        "has_timezone": False,
        "has_microseconds": True,
    },
    # === Standard datetime ===
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?\b",
        "format": "%Y-%m-%d %H:%M:%S.%f",
        "name": "standard_datetime",
        "base_confidence": 0.80,
        "specificity": "medium",
        "has_timezone": False,
        "has_microseconds": True,
    },
    # === Nginx error ===
    {
        "pattern": r"\b\d{4}/\d{2}/\d{2}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%Y/%m/%d %H:%M:%S",
        "name": "nginx_error",
        "base_confidence": 0.78,
        "specificity": "medium",
        "has_timezone": False,
        "has_microseconds": False,
    },
    # === US/Non-ISO formats (lower confidence due to ambiguity) ===
    {
        "pattern": r"\b\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%m-%d-%Y %H:%M:%S",
        "name": "us_datetime",
        "base_confidence": 0.65,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%m/%d/%Y %H:%M:%S",
        "name": "us_slash_datetime",
        "base_confidence": 0.65,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{4}/\d{2}/\d{2}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%Y/%m/%d %H:%M:%S",
        "name": "slash_datetime",
        "base_confidence": 0.75,
        "specificity": "medium",
        "has_timezone": False,
        "has_microseconds": False,
    },
    # === Syslog formats ===
    {
        "pattern": r"\b[A-Za-z]{3}\s+\d{1,2}\s+\d{4}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%b %d %Y %H:%M:%S",
        "name": "syslog_long",
        "base_confidence": 0.82,
        "specificity": "medium",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b[A-Za-z]{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\b",
        "format": "%b %d %H:%M:%S",
        "name": "syslog_short",
        "base_confidence": 0.70,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    # === Unix timestamps ===
    {
        "pattern": r"\b\d{16}\b",
        "format": "unix_timestamp_us",
        "name": "unix_microseconds",
        "base_confidence": 0.75,
        "specificity": "medium",
        "has_timezone": True,  # Unix timestamps are inherently UTC
        "has_microseconds": True,
    },
    {
        "pattern": r"\b\d{13}\b",
        "format": "unix_timestamp_ms",
        "name": "unix_milliseconds",
        "base_confidence": 0.80,
        "specificity": "medium",
        "has_timezone": True,
        "has_microseconds": True,
    },
    {
        "pattern": r"\b\d{10}\b",
        "format": "unix_timestamp",
        "name": "unix_seconds",
        "base_confidence": 0.85,
        "specificity": "medium",
        "has_timezone": True,
        "has_microseconds": False,
    },
    # === Date only (lower confidence - incomplete) ===
    {
        "pattern": r"\b\d{4}-\d{2}-\d{2}\b",
        "format": "%Y-%m-%d",
        "name": "iso_date",
        "base_confidence": 0.60,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{4}/\d{2}/\d{2}\b",
        "format": "%Y/%m/%d",
        "name": "slash_date",
        "base_confidence": 0.55,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    {
        "pattern": r"\b\d{2}/\d{2}/\d{4}\b",
        "format": "%m/%d/%Y",
        "name": "us_date",
        "base_confidence": 0.45,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": False,
    },
    # === Time only (lowest confidence - very incomplete) ===
    {
        "pattern": r"\b\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?\b",
        "format": "%H:%M:%S.%f",
        "name": "time_only",
        "base_confidence": 0.35,
        "specificity": "low",
        "has_timezone": False,
        "has_microseconds": True,
    },
]
